export const texts = [
  "The sky was a deep shade of blue, the kind that lingered just before the sun began to set. As she walked down the street, the sound of her heels echoed in the empty spaces between buildings. She couldn't help but feel a sense of unease, as if she was being watched. With each step, her heart beat a little faster.",
  "The rain was relentless, tapping at the windowpanes like an impatient visitor. She wrapped herself in a blanket and sipped her tea, watching the world turn grey outside. It was a day for curling up with a good book, for shutting out the noise of the world and getting lost in another world.",
  "The waves crashed against the shore, a constant reminder of the power of the sea. She breathed in the salty air and felt the sand between her toes, grateful for the escape from the city. There was something cleansing about the ocean, something that made her feel small in the best possible way.",
  "The city was alive with the sound of music, a mix of genres blending together in a symphony of noise. She weaved her way through the crowds, taking in the sights and smells of the street vendors. It was a chaotic world, but in that chaos she found a sense of peace.",
  "The forest was a place of mystery, where the trees loomed tall and the branches intertwined like a living tapestry. She hiked for hours, feeling the crunch of leaves under her feet and the warmth of the sun on her face. In that moment, she was a part of something greater than herself.",
  "The room was silent except for the ticking of the clock. She sat at her desk, staring at the blank page in front of her. She had been struggling with writer's block for weeks, unable to put pen to paper. But as the minutes ticked by, the words began to flow and the story took shape.",
  "The desert was a harsh and unforgiving landscape, the sun beating down on her like a punishment. She trudged through the sand, feeling each grain scrape against her skin. But in that emptiness she found a kind of clarity, a freedom from the noise of the world.",
  "The train whistled in the distance, a melancholy sound that echoed through the hills. She watched as it chugged past, wondering where it was going and who was aboard. There was a sense of adventure in that unknown, a sense of possibility.",
  "The snow fell softly, blanketing the world in white. She wrapped herself in a coat and stepped outside, feeling the crunch of snow under her boots. It was a moment of pure serenity, a reminder of the beauty of the world.",
  "The sun set over the horizon, a final burst of orange and red before darkness descended. She sat on the beach, feeling the sand between her toes and watching as the stars began to twinkle in the sky. It was a moment of peace, a moment to simply be.",
  "The city skyline was a glittering jewel, a testament to human achievement. She watched from the top of a skyscraper, feeling a sense of awe at the sheer scale of it all. It was a world of infinite possibility, a world where anything was possible.",
  "The old bookstore was a treasure trove of stories, the shelves groaning under the weight of books. She lost herself among the pages, discovering new worlds and new characters. In that moment, she was anything she wanted to be."
]

